import type { LucideIcon } from 'lucide-react';
import {
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUpFromLine,
  AudioWaveform,
  Bell,
  Calendar,
  Cctv,
  ChartColumn,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheckBig,
  CircleX,
  Clock,
  Copy,
  Cpu,
  EllipsisVertical,
  Eye,
  EyeOff,
  FileQuestion,
  FileSearch,
  FileSearch2,
  FileText,
  Frown,
  IdCard,
  Info,
  KeyRound,
  LayoutDashboard,
  LogOut,
  Menu,
  MonitorX,
  Pencil,
  Plus,
  Power,
  RefreshCcw,
  RotateCw,
  Search,
  Settings,
  ShieldCheck,
  Smile,
  Thermometer,
  Trash,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  User,
  UserCog,
  VideoOff,
  Wallet,
  Zap,
} from 'lucide-react';

/**
 * Orbie UI KIT — `icons` page (Figma node `9:11137`).
 * Slugs match layer names after `Icon / …` (Lucide-aligned).
 * `gpu`: Figma has a GPU icon; Lucide doesn't have a matching icon, so we approximate it with `Cpu`.
 */
export const orbieIconMap = {
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-from-line': ArrowUpFromLine,
  'audio-waveform': AudioWaveform,
  bell: Bell,
  calendar: Calendar,
  cctv: Cctv,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle-alert': CircleAlert,
  'circle-check-big': CircleCheckBig,
  'circle-x': CircleX,
  clock: Clock,
  copy: Copy,
  gpu: Cpu,
  'ellipsis-vertical': EllipsisVertical,
  eye: Eye,
  'eye-off': EyeOff,
  'file-question': FileQuestion,
  'file-search': FileSearch,
  'file-search-2': FileSearch2,
  'file-text': FileText,
  frown: Frown,
  'id-card': IdCard,
  info: Info,
  'key-round': KeyRound,
  'layout-dashboard': LayoutDashboard,
  'log-out': LogOut,
  menu: Menu,
  'monitor-x': MonitorX,
  pencil: Pencil,
  plus: Plus,
  power: Power,
  'refresh-ccw': RefreshCcw,
  'rotate-cw': RotateCw,
  search: Search,
  settings: Settings,
  'shield-check': ShieldCheck,
  smile: Smile,
  thermometer: Thermometer,
  trash: Trash,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  user: User,
  'user-cog': UserCog,
  'video-off': VideoOff,
  wallet: Wallet,
  warning: TriangleAlert,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type OrbieIconName = keyof typeof orbieIconMap;

export const ORBIE_ICON_NAMES = Object.keys(orbieIconMap).sort() as OrbieIconName[];
